### ISSUE TITLE
Octolife Github report authorization not working

### ISSUE THREAD

**Issue by Josee9988** [krasimir/octolife#4]
I did manage to authorize octolife a couple of days ago, and this was my first time using this tool.

But, today I wanted to see my profile and I suddenly realized the "90 days" authorization was gone, even though I authorized it a couple of days ago... I clicked on "Authorize Octolife GitHub app to see the report", but that button seems to not work at all, as It redirects me to the same page all over again.

Video prove: https://i.imgur.com/fMFUuHi.mp4

**Comment by krasimir** [comment]
Can you please try clearing your session/local storage

**Comment by Josee9988** [comment]
It didn't work again. But in the chrome developers tools I could see that I got redirected to `https://octolife.vercel.app/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=octolife` i don't know if that might help you

**Comment by krasimir** [comment]
Thank you @Josee9988. Your last comment was the key. Looks like Vercel redirected from now.sh to vercel.app now. It wasn't like that before. And the oauth callback for the app was set to now.sh. Now it's fixed.

**Comment by Josee9988** [comment]
Now it works, thanks!
